### ISSUE TITLE
Install problem from composer

### ISSUE THREAD

**Issue by sallfris** [Edofre/yii2-fullcalendar-scheduler#17]
`composer require edofre/yii2-fullcalendar-scheduler "1.1.x-dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for edofre/yii2-fullcalendar-scheduler 1.1.x-dev -> satisfiable by edofre/yii2-fullcalendar-scheduler[1.1.x-dev].
    - edofre/yii2-fullcalendar-scheduler 1.1.x-dev requires npm-asset/fullcalendar-scheduler 1.7.1 -> no matching package found.
`

**Comment by Edofre** [comment]
Sorry for the late response, was on holiday.

The fxp/composer-asset plugin is required for this package to install properly. This plugin enables you to download bower packages through composer.

You can install it using this command:
composer global require "fxp/composer-asset-plugin:^1.4.0”

**Comment by Edofre** [comment]
Installation works without problems for me.
