### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pnd178** [Edofre/yii2-fullcalendar-scheduler#19]
Hi,

How and where can I put the fullcalendar license?

thank you,
best regards,

**Comment by Edofre** [comment]
Sorry for the late reply, you should add the schedulerLicenseKey to the options of the fullcalendar.

```php
<?= \edofre\fullcalendarscheduler\FullcalendarScheduler::widget([
    'clientOptions' => [
        'schedulerLicenseKey' => 'GPL-My-Project-Is-Open-Source'
    ],
]);
?>
```
