### ISSUE TITLE
requires bower-asset/fullcalendar

### ISSUE THREAD

**Issue by miniportal** [Edofre/yii2-fullcalendar-scheduler#2]
I'm trying to install this extension, but I'm getting this error:

Problem 1
    - edofre/yii2-fullcalendar-scheduler V1.1.1 requires bower-asset/fullcalendar v2.7.2 -> satisfiable by bower-asset/fullcalendar[v2.7.2].
    - edofre/yii2-fullcalendar-scheduler dev-master requires bower-asset/fullcalendar v2.7.2 -> satisfiable by bower-asset/fullcalendar[v2.7.2].
    - edofre/yii2-fullcalendar-scheduler 1.1.x-dev requires bower-asset/fullcalendar v2.7.2 -> satisfiable by bower-asset/fullcalendar[v2.7.2].
    - edofre/yii2-fullcalendar-scheduler v1.1.0.x-dev requires bower-asset/fullcalendar v2.7.2 -> satisfiable by bower-asset/fullcalendar[v2.7.2].
    - Conclusion: don't install bower-asset/fullcalendar v2.7.2
    - Installation request for edofre/yii2-fullcalendar-scheduler @dev -> satisfiable by edofre/yii2-fullcalendar-scheduler[V1.1.1, dev-master, 1.1.x-dev, v1.1.0.x-dev].

Can anyone help me?

**Comment by Edofre** [comment]
Can I see your composer.json file? I just tried to install v1.1.1 and @dev versions and they installed without a problem.

I also see that the bower-asset/fullcalendar: v2.7.2 is in the dependencies so I don't see why it would fail.

**Comment by Edofre** [comment]
I've updated all the fullcalendar dependencies in the new v1.1.2 version. Maybe that one will work for you.
