### ISSUE TITLE
Cannot remove License information

### ISSUE THREAD

**Issue by InfoButler-LinaLu** [Edofre/yii2-fullcalendar-scheduler#20]
I tried the suggestion from fullCalendar official website, trying to remove the license key warning like follow:

```
$('#calendar').fullCalendar({
  schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source'
});
```

However, the warning message still remains.  Is there any way to remove it?

**Comment by Edofre** [comment]
Sorry for the late reply, you should add the schedulerLicenseKey to the options of the fullcalendar.

```php
<?= \edofre\fullcalendarscheduler\FullcalendarScheduler::widget([
    'clientOptions' => [
        'schedulerLicenseKey' => 'GPL-My-Project-Is-Open-Source'
    ],
]);
?>
```
