### ISSUE TITLE
Disable resizing

### ISSUE THREAD

**Issue by artyomeg** [Edofre/yii2-fullcalendar-scheduler#22]
Hello, how can i disable resizing?
![image](https://user-images.githubusercontent.com/2463080/38634603-adaa05c8-3dcb-11e8-9965-e9a061e11142.png)
Perhaps there is a way to initially remove from the event the class "fc-resizable"

**Comment by Edofre** [comment]
Hello, in your event you can set the 'durationEditable' attribute to false.

**Comment by artyomeg** [comment]
It did not help.

`
    echo FullcalendarScheduler::widget([
        'header' => [
            'left'   => 'prev, next, btn-today',
            'center' => 'title',
            'right'  => 'agendaDay, agendaTwoDay, agendaWeek, month, btn-count-specialist, btn-add-specialist',
        ],
        'clientOptions' => [
            'customButtons' => [
                'btn-today' => [
                    'text' => 'Сегодня',
                ],
                'btn-count-specialist' => [
                    'text' => $count_specialists_in_journal,
                ],
                'btn-add-specialist' => [
                    'text' => 'Добавить специалиста'
                ]
            ],
            'titleFormat'       => 'D MMM, dddd',
            'firstDay'          => 1,
            'monthNamesShort'   => ['янв', 'февр', 'марта', 'апр', 'мая', 'июня', 'июля', 'авг', 'сент', 'окт', 'нояб', 'дек'],
            'height'            => 'auto',
            'businessHours'     => false,
            'locale'            => 'ru',
            'defaultView'       => 'agendaDay',
            'defaultDate'       => $date,
            'slotLabelFormat'   => 'HH:mm',
            'allDaySlot'        => false,
            'minTime'           => $timetable_cabinet->start_time,
            'maxTime'           => date('H:i', strtotime($timetable_cabinet->stop_time . ' + 15 min')),
            'slotDuration'      => $slot_interval,
            'slotLabelInterval' => $slot_interval,
            'nowIndicator'      => true,
            // убираем изменение времени сеанса, если потянуть за низ сеанса
            'durationEditable'  => false,
            'editable'          => true,
            'loading'           => new \yii\web\JsExpression("
                function(isLoading, view) {
                    journalLoading(isLoading);
                }"
            ),
            'views' => [
                'agendaTwoDay' => [
                    'type'     => 'agenda',
                    'duration' => ['days' => 2],
                    // views that are more than a day will NOT do this behavior by default
                    // so, we need to explicitly enable it
                    'groupByResource' => true,
                    //// uncomment this line to group by day FIRST with resources underneath
                    //'groupByDateAndResource' => true,
                ],
            ],
            'resources'      => Url::to(['journal/ajax-get-specialists']),
            'events'         => Url::to(['journal/ajax-get-entries']),
            'eventDragStart' => new \yii\web\JsExpression("
                function(event){
                    eventDragStart(event);
                }
            "),
            'eventDrop' => new \yii\web\JsExpression("
                function(event, delta, revertFunc,jsEvent, ui, view) {
                    eventDrop(event, delta, revertFunc, jsEvent, ui, view);
                }
            "),
            'resourceAreaWidth' => '70%',
            'eventRender'       => new \yii\web\JsExpression("
                function(resource, cellEls) {
                    eventRender(resource, cellEls);
                }
            "),
            'dayClick' => new \yii\web\JsExpression("
                function(date, jsEvent, view, resource) {
                    dayClick(date, jsEvent, view, resource);
                }
            "),
            'eventClick' => new \yii\web\JsExpression("
                function(calEvent, jsEvent, view) {
                    eventClick(calEvent, jsEvent, view);
                }
            ")
        ]
    ]);
`

![image](https://user-images.githubusercontent.com/2463080/38676108-ac38ecee-3e62-11e8-8c52-e3d021fde35f.png)

**Comment by artyomeg** [comment]
![image](https://user-images.githubusercontent.com/2463080/38676151-ccc0be10-3e62-11e8-9ad3-880d508cea23.png)
![image](https://user-images.githubusercontent.com/2463080/38676170-d49eae1c-3e62-11e8-9ea2-27fc98569fa3.png)
![image](https://user-images.githubusercontent.com/2463080/38676179-dab29840-3e62-11e8-95c9-5a99ce4964df.png)

Better to whatch.

**Comment by Edofre** [comment]
@artyomeg 

You should put the 'durationEditable' as an option in your Event, not in the Fullcalendar widget. In your /journal/ajax-get-entries you are probably creating Event objects, these objects should have the "durationEditable" => false option.

**Comment by artyomeg** [comment]
Thanks!
