### ISSUE TITLE
locale-all.js not found after update

### ISSUE THREAD

**Issue by martinlaregina** [Edofre/yii2-fullcalendar-scheduler#6]
Hi !!

After run composer update, i have an error loading file locale-all.js.
I check assets and exist but into fullcalendar/dist directory.
![console](https://cloud.githubusercontent.com/assets/11611304/21311629/694cc50c-c5e8-11e6-9aed-3d5326f213dc.jpg)
![composer_update](https://cloud.githubusercontent.com/assets/11611304/21311630/69505d0c-c5e8-11e6-9b8d-fcb8698f02db.jpg)

Tkanks a lot

**Comment by Edofre** [comment]
Hi @martinlaregina 

I've created a new release, if you specify the V1.1.4 version in your composer.json it should be fixed.

Thank you for notifying me 👍
